// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXh39drqOwpS8K9MvoEpimEuqCFIgO4Y',
    appId: '1:379102232982:web:4ce7c6f3c58b10fe6f5db7',
    messagingSenderId: '379102232982',
    projectId: 'kozshifo-32e6f',
    authDomain: 'kozshifo-32e6f.firebaseapp.com',
    storageBucket: 'kozshifo-32e6f.firebasestorage.app',
    measurementId: 'G-4B3EF13GP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zRsJC0IJ8GInw-wQHYa8L16lHEkQU8w',
    appId: '1:379102232982:android:34c29ce0acfc70336f5db7',
    messagingSenderId: '379102232982',
    projectId: 'kozshifo-32e6f',
    storageBucket: 'kozshifo-32e6f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXh39drqOwpS8K9MvoEpimEuqCFIgO4Y',
    appId: '1:379102232982:web:7069b12e88475b476f5db7',
    messagingSenderId: '379102232982',
    projectId: 'kozshifo-32e6f',
    authDomain: 'kozshifo-32e6f.firebaseapp.com',
    storageBucket: 'kozshifo-32e6f.firebasestorage.app',
    measurementId: 'G-9E028GWX0V',
  );
}
