"""patient_crm_fields_phone2_passport_pinfl_profession_leadsource

Revision ID: 573b0c777a5e
Revises: 759124df8395
Create Date: 2026-06-13 13:40:48.934659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573b0c777a5e'
down_revision: Union[str, Sequence[str], None] = '759124df8395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone2', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('passport', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('pinfl', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('lead_source', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_lead_source'), ['lead_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_pinfl'), ['pinfl'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_pinfl'))
        batch_op.drop_index(batch_op.f('ix_patients_lead_source'))
        batch_op.drop_column('profession')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('pinfl')
        batch_op.drop_column('passport')
        batch_op.drop_column('phone2')

    # ### end Alembic commands ###
