"""tz_completion_attendance_finance_calls_discounts

Revision ID: 759124df8395
Revises: c8b78621c775
Create Date: 2026-06-12 23:09:08.119788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759124df8395'
down_revision: Union[str, Sequence[str], None] = 'c8b78621c775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_events_user_id'), ['user_id'], unique=False)

    op.create_table('call_records',
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_normalized', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('handled_by_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_phone_normalized'), ['phone_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_started_at'), ['started_at'], unique=False)

    op.create_table('expenses',
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payroll_user_id', sa.Uuid(), nullable=True),
    sa.Column('payroll_month', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payroll_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_user_id', 'payroll_month', name='uq_expense_payroll_user_month')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)

    with op.batch_alter_table('eye_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('od_va_own', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('os_va_own', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('visual_field', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_percent', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_reason', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('discount_reason')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salary_percent')

    with op.batch_alter_table('eye_exams', schema=None) as batch_op:
        batch_op.drop_column('visual_field')
        batch_op.drop_column('os_va_own')
        batch_op.drop_column('od_va_own')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_index(batch_op.f('ix_expenses_branch_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_started_at'))
        batch_op.drop_index(batch_op.f('ix_call_records_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_call_records_patient_id'))

    op.drop_table('call_records')
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_events_occurred_at'))

    op.drop_table('attendance_events')
    # ### end Alembic commands ###
